### ISSUE TITLE
Does not work with KDBX 3.1 format

### ISSUE THREAD

**Issue by pludi** [Narigo/keepass-diff#24] opened 2020-07-02 06:53 UTC
# What is happening
When comparing databases with at least 1 having a KDBX 3.1 DB format, `keepass-diff` apparently enters an infinite loop

# What should happen
Output of the differences.

# Steps to reproduce
1.  Create 2 databases, explicitly selecting KDBX 3.1 format
2.  Compare them using `keepass-diff` without any special options

# Versions used
-   KeePassXC: 2.4.3
-   `keepass-diff`: 1.0.0
-   `cargo`/`rustc`: 1.41.0

**Comment by Narigo** [comment] 2020-07-05 20:28
Thanks for the report @pludi ! Could you create reproducer files for this?
This sounds like a limitation of the underlying [keepass-rs](https://github.com/sseemayer/keepass-rs) dependency and it probably should be addressed there. Still, we might want to add a test for this scenario in here.

**Comment by pludi** [comment] 2020-07-06 13:07
Had to `gzip` them to get past GitHubs filter.

[Test1.kdbx.gz](https://github.com/Narigo/keepass-diff/files/4879056/Test1.kdbx.gz), Password: `Test1`
[Test2.kdbx.gz](https://github.com/Narigo/keepass-diff/files/4879057/Test2.kdbx.gz), Password: `Test2`

**Comment by Narigo** [comment] 2020-07-06 23:55
Hmm, works for me but takes 5 minutes or so with `RUSTFLAGS="-C target-cpu=native"`. From my debugging, it looks like it has a very high number of `transformation_rounds` in the headers of the files, so it runs the encryption very often. This needs to be addressed in `keepass-rs`, so I have opened [issue 25](https://github.com/sseemayer/keepass-rs/issues/25).

**Comment by Narigo** [comment] 2020-11-14 00:09
@pludi maybe you want to re-check with version `1.0.1` now. It should have the rustflags set already. It's still slow but I could at least use it on your test files. I have added the test files to the tests as well now, to see that they can be opened.

**Comment by pludi** [comment] 2020-11-24 15:27
Ran it after compiling with the optimization `RUSTFLAGS` you've posted: ```

**Comment by Narigo** [comment] 2021-02-11 10:19
Okay, I will close this now, the tests run way better in the newest version, with the flags set in `.cargo/config.toml`.

**Closed by Narigo** 2021-02-11 10:19 UTC
Labels: ⚠︎ Blocked
